<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Run</name>
   <tag></tag>
   <elementGuidId>cf35c248-7db2-4a4f-804e-2ec6e6100563</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#runbtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='runbtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Run ❯&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>34a4a5ed-7241-43b7-a00b-266dfe932988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>runbtn</value>
      <webElementGuid>7701d0c4-4517-49dd-9cf8-0ec591aef3dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w3-button w3-bar-item w3-hover-white w3-hover-text-green ga-tryit</value>
      <webElementGuid>8761af51-6292-4178-bd11-8a5806e4fe43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>submitTryit(1);uic_r_p();</value>
      <webElementGuid>498d9bc8-6969-43de-8170-d3fcf5b6b6c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Run ❯</value>
      <webElementGuid>9547c04f-ab83-4662-8658-439e1d003a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;runbtn&quot;)</value>
      <webElementGuid>e9ab7381-15b4-4c4e-9d37-67d3d67adf67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='runbtn']</value>
      <webElementGuid>94be0520-3704-4849-9311-3444425e30bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='own'])[1]/preceding::button[1]</value>
      <webElementGuid>edf5224a-5b54-4102-9abf-2d679d72bf1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Run ❯']/parent::*</value>
      <webElementGuid>b5f1f9a3-1249-4a16-8b51-bfbf3f2dbd6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>59af12b4-f651-4969-b74a-a25ae1767c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'runbtn' and (text() = 'Run ❯' or . = 'Run ❯')]</value>
      <webElementGuid>7ffb2314-e0ca-426e-a653-ad26f009687f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
