<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search field_tnb-google-search-input</name>
   <tag></tag>
   <elementGuidId>c5ad7747-4006-4abd-8eb7-e1165e090cc5</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tnb-google-search-input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;tnb-google-search-input&quot;)[count(. | //input[@id = 'tnb-google-search-input' and @type = 'text' and @placeholder = 'Search...' and @autocomplete = 'off' and @onkeydown = 'TopNavBar.googleSearchAttachKeyPressHandler(event)' and @aria-label = 'Search field' and @oninput = 'TopNavBar.searchWithSuggestions(this)' and @onfocus = 'TopNavBar.searchWithSuggestions(this)' and @onblur = 'TopNavBar.searchFieldLostFocus(event)' and @ref_element = 'Object Repository/Page_W3Schools Tryit Editor/iframe']) = count(//input[@id = 'tnb-google-search-input' and @type = 'text' and @placeholder = 'Search...' and @autocomplete = 'off' and @onkeydown = 'TopNavBar.googleSearchAttachKeyPressHandler(event)' and @aria-label = 'Search field' and @oninput = 'TopNavBar.searchWithSuggestions(this)' and @onfocus = 'TopNavBar.searchWithSuggestions(this)' and @onblur = 'TopNavBar.searchFieldLostFocus(event)' and @ref_element = 'Object Repository/Page_W3Schools Tryit Editor/iframe'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tnb-google-search-input']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2bc93b90-34a7-448f-ad9c-c3bb05520104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tnb-google-search-input</value>
      <webElementGuid>b2289179-d63e-4ee8-8542-326e70ea865d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>79f520ff-f849-478a-8422-e112f1cc2162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>dfe1f49c-110a-4b25-a855-ae4f65015dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3e1f9ec8-ca91-45e2-9fe1-efd49a505ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>TopNavBar.googleSearchAttachKeyPressHandler(event)</value>
      <webElementGuid>6be4bca1-cb59-4c55-a60c-2164839acf27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search field</value>
      <webElementGuid>c72fe6a7-3295-4ad8-bd9b-e948f6b6ac8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>TopNavBar.searchWithSuggestions(this)</value>
      <webElementGuid>107122ab-dd94-43b9-a9ab-adeb7e3fe80f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>TopNavBar.searchWithSuggestions(this)</value>
      <webElementGuid>504b72cc-9109-4a92-ac58-5ce13482dbc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>TopNavBar.searchFieldLostFocus(event)</value>
      <webElementGuid>8e3768d9-7438-4925-853e-8d977be8a0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tnb-google-search-input&quot;)</value>
      <webElementGuid>dd6ecbc5-6e4f-420a-a406-f540b5e086d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_W3Schools Tryit Editor/iframe</value>
      <webElementGuid>d4435ec6-8285-4fbf-bdc1-c3187217eaa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tnb-google-search-input']</value>
      <webElementGuid>cffd4675-17c3-48a3-9e8a-6d4b3981d647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tnb-google-search-inner-container']/input</value>
      <webElementGuid>2b68e1c0-4504-48e8-8509-1d1cab68ca84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6d3a786c-eab1-4ec7-9923-934cd466c4fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tnb-google-search-input' and @type = 'text' and @placeholder = 'Search...']</value>
      <webElementGuid>e1b231aa-a8c0-463b-afc7-973c92247dfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
