<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea</name>
   <tag></tag>
   <elementGuidId>68d61af6-3474-46b7-a52c-1396e2c0e9cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.CodeMirror.cm-s-default.CodeMirror-wrap.CodeMirror-focused > div > textarea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='textareawrapper']/div/div/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7b7fc25c-9f5c-4e71-a5ff-dfc3e4a2ae85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e939c22b-1f19-4e86-b249-5909db6b4949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ffcee4b6-130c-4fd3-9d38-65aaf1d14544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a7a041b4-803a-4318-a9fb-e6960e7de4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>540226a6-ec53-479d-a8a8-4bbd595724e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textareawrapper&quot;)/div[@class=&quot;CodeMirror cm-s-default CodeMirror-wrap CodeMirror-focused&quot;]/div[1]/textarea[1]</value>
      <webElementGuid>2d1fbce5-528f-4d35-bddf-c6ca82885b12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='textareawrapper']/div/div/textarea</value>
      <webElementGuid>e43b0ddb-504b-4151-9ebc-4c0205fe74a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/textarea</value>
      <webElementGuid>0e283054-f964-4995-8022-1004789b6a75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
